### ISSUE TITLE
Agent installation failed

### ISSUE THREAD

**Issue by lionelmace** [terraform-ibm-modules/terraform-ibm-scc-workload-protection-agent#310]
I faced the following error when trying to deployed Workload Protection agent with this code
https://github.com/lionelmace/ibm-cloud-native/blob/main/terraform/observability-monitoring.tf

```
2025/04/28 09:31:50 Terraform apply | module.scc_wp_agent.helm_release.scc_wp_agent: Still creating... [24m40s elapsed]
 2025/04/28 09:32:00 Terraform apply | module.scc_wp_agent.helm_release.scc_wp_agent: Still creating... [24m50s elapsed]
 2025/04/28 09:32:10 Terraform apply | module.scc_wp_agent.helm_release.scc_wp_agent: Still creating... [25m0s elapsed]
 2025/04/28 09:32:20 Terraform apply | 
 2025/04/28 09:32:20 Terraform apply | Warning: Helm release "" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then run Terraform again.
 2025/04/28 09:32:20 Terraform apply | 
 2025/04/28 09:32:20 Terraform apply |   with module.scc_wp_agent.helm_release.scc_wp_agent,
 2025/04/28 09:32:20 Terraform apply |   on .terraform/modules/scc_wp_agent/main.tf line 35, in resource "helm_release" "scc_wp_agent":
 2025/04/28 09:32:20 Terraform apply |   35: resource "helm_release" "scc_wp_agent" {
 2025/04/28 09:32:20 Terraform apply | 
 2025/04/28 09:32:20 Terraform apply | 
 2025/04/28 09:32:20 Terraform apply | Error: context deadline exceeded
 2025/04/28 09:32:20 Terraform apply | 
 2025/04/28 09:32:20 Terraform apply |   with module.scc_wp_agent.helm_release.scc_wp_agent,
 2025/04/28 09:32:20 Terraform apply |   on .terraform/modules/scc_wp_agent/main.tf line 35, in resource "helm_release" "scc_wp_agent":
 2025/04/28 09:32:20 Terraform apply |   35: resource "helm_release" "scc_wp_agent" {
 2025/04/28 09:32:20 Terraform apply | 
 2025/04/28 09:32:20 [1m[31mTerraform APPLY error: Terraform APPLY errorexit status 1[39m[0m
 2025/04/28 09:32:20 [1m[31mCould not execute job: Error : Terraform APPLY errorexit status 1[39m[0m
```

What could be wrong?

**Comment by ocofaigh** [comment]
@lionelmace That error is telling me that the pods did not come up. So you need to log into the cluster and check why

**Comment by lionelmace** [comment]
Here are the logs for the pod ice-wp-agent

```
 * Setting up /usr/src links from host                                                                                                                                                                          │
│ * Kernel headers not found in /host/lib/modules/5.14.0-427.64.1.el9_4.x86_64/build, continuing anyway                                                                                                          │
│ * Loading kernel probe                                                                                                                                                                                         │
│ * Unloading sysdigcloud-probe, if present                                                                                                                                                                      │
│ * Running dkms install for draios-agent                                                                                                                                                                        │
│                                                                                                                                                                                                                │
│ Error! Your kernel headers for kernel 5.14.0-427.64.1.el9_4.x86_64 cannot be found at /lib/modules/5.14.0-427.64.1.el9_4.x86_64/build or /lib/modules/5.14.0-427.64.1.el9_4.x86_64/source.                     │
│ Please install the linux-headers-5.14.0-427.64.1.el9_4.x86_64 package or use the --kernelsourcedir option to tell DKMS where it's located.                                                                     │
│   Running dkms build failed, couldn't find /var/lib/dkms/draios-agent/13.8.1/build/make.log                                                                                                                    │
│ * Trying to load a system sysdigcloud-probe, if present                                                                                                                                                        │
│ * Trying to find precompiled sysdigcloud-probe for 5.14.0-427.64.1.el9_4.x86_64                                                                                                                                │
│ * Evaluating override of environment variables                                                                                                                                                                 │
│ * Looking for kernel configuration                                                                                                                                                                             │
│   Found kernel config at /lib/modules/5.14.0-427.64.1.el9_4.x86_64/config                                                                                                                                      │
│ * Trying to find precompiled sysdigcloud-probe for 5.14.0-427.64.1.el9_4.x86_64                                                                                                                                │
│ * Trying to download precompiled module from https://download.sysdig.com/stable/sysdig-probe-binaries/sysdigcloud-probe-13.8.1-x86_64-5.14.0-427.64.1.el9_4.x86_64-1f965e3d615f8b35db502b4057cbe812.ko         │
│ Download of sysdigcloud-probe for version 13.8.1 failed.                                                                                                                                                       │
│ curl: (22) The requested URL returned error: 404                                                                                                                                                               │
│ Cannot load the probe                                                                                                                                                                                          │
│ stream closed EOF for ibm-scc-wp/icn-wp-agent-c8khm (sysdig-agent-kmodule)
```

**Comment by lionelmace** [comment]
Yes it does.

**Comment by ctolon22** [comment]
This is because the pre-built module is not compiled. Checking...

**Comment by ctolon22** [comment]
This is being fixed in our side. Try again in a few hours

**Comment by lionelmace** [comment]
@ctolon22 do I just need to re-run `terraform apply` ? Let me know when the fix is out. I'd rather try when I know for sure this is fixed ;-)

**Comment by ocofaigh** [comment]
@lionelmace When the fix is out you should be able to re-run `terraform apply` and it should force a helm upgrade and recreate the pods. Right @ctolon22 ? There isn't a new version required right?

**Comment by lionelmace** [comment]
@ctolon22 I made a fresh new deployment today and it still failed...

**Comment by lionelmace** [comment]
It seems to be fixed on my side. @ocofaigh have you tested it?
